SELECT J.FLAVOR
FROM FIRST_HALF
JOIN (SELECT FLAVOR, sum(TOTAL_ORDER) AS SUM
      FROM JULY
      GROUP BY FLAVOR) AS J
ON FIRST_HALF.FLAVOR = J.FLAVOR
ORDER BY FIRST_HALF.TOTAL_ORDER + J.SUM DESC
LIMIT 3