-- FLOOR(num) : 소수점 이하 값을 버린다.
SELECT CAR.CAR_ID, CAR.CAR_TYPE, FLOOR(CAR.DAILY_FEE * (1-(PLAN.DISCOUNT_RATE / 100)) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING min(START_DATE) > DATE('2022-11-30') OR max(END_DATE) < DATE('2022-11-01')) AS HISTORY
ON CAR.CAR_ID = HISTORY.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE AND PLAN.DURATION_TYPE = '30일 이상'
GROUP BY CAR.CAR_ID
HAVING CAR.CAR_TYPE in ('세단', 'SUV') AND FEE >= 500000 AND FEE<2000000
ORDER BY FEE DESC, CAR.CAR_TYPE, CAR.CAR_ID DESC