-- UNION : 두 개 이상의 SELECT 문의 결과를 하나의 결과 집합으로 결합.
-- 각 SELECT문에서 반환된 모든 행을 합치되, 중복된 행을 제거한다.
-- 만약 중복된 행을 제거하지 않고 모두 반환하고 싶다면 UNION ALL을 사용한다.

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3

UNION

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;