-- DISTINCT : 전체 행의 중복을 제거
SELECT ONL.YEAR AS YEAR, ONL.MONTH, GENDER, count(*) AS USERS
FROM USER_INFO, (SELECT DISTINCT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH FROM ONLINE_SALE) AS ONL
WHERE USER_INFO.USER_ID = ONL.USER_ID AND GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER